### ISSUE TITLE
Thinner wrapper for Unicorn

### ISSUE THREAD

**Issue by tathanhdinh** [ekse/unicorn-rs#49]
I still do not understand why the struct 

https://github.com/ekse/unicorn-rs/blob/4814a4f41db825c8123905006e71ffa2761a34d5/src/lib.rs#L380-L389

needs to store callbacks. Indeed, I've removed them, the code still compiles but tests fail :(

Are there reasons for the existence of these callback maps? I think that they might help to keep the lifetime of callback closures? (if "yes", why isn't the compiler able to detect the problem when I remove them)

Many thanks for any response.

**Comment by ekse** [comment]
I forgot to answer your question. It is as you guessed to keep the hooks for the duration of their use. The compiler is unable to track lifetimes because we are passing pointers to the objects, not references. As far as I know this is not possible with FFI.

I'm closing the issue as it was a question, feel free to reopen it if you want to discuss this further.
